apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: todo-backend:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          envFrom:
            - secretRef:
                name: todo-backend-env
          env:
            - name: DATABASE_URL
              value: "postgresql+psycopg://todo:todo123@todo-db:5432/todoapp"
            - name: PORT
              value: "8002"
          readinessProbe:
            tcpSocket:
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8002
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend
spec:
  selector:
    app: todo-backend
  ports:
    - name: http
      port: 8002
      targetPort: 8002
  type: ClusterIP
